### ISSUE TITLE
Local install not working

### ISSUE THREAD

**Issue by Echolink50** [anothermartz/Easy-Wav2Lip#10]
Thanks for this. It is really great. I ran the colab and it was very good. I tried the local install on a Windows 10 machine with RTX 2060 12GB and. After filling in the config.ini I am getting a no module named torch error.

**Comment by anothermartz** [comment]
Make sure Cuda 12.2 or 12.3 is installed, this should install automatically when installing the latest Nvidia drivers.

I'll add a check for this in Easy-Wav2Lip.bat for the next version :)

Let me know if there are still issues.

**Comment by Echolink50** [comment]
Ok thanks. I didn't know Cuda 12.2 or higher was needed. I will try again. Thanks

**Comment by Echolink50** [comment]
Upgraded to Cuda 12.2. The automagic .bat file is still not installing for me. Torch isn't being set up. Getting a dlib pep 517 error. Do you have a manual install requirement.txt file or something?

Edt: Should ask if VS 2022 is needed? I have 2019.

**Comment by anothermartz** [comment]
> Upgraded to Cuda 12.2. The automagic .bat file is still not installing for me. Torch isn't being set up. Getting a dlib pep 517 error. Do you have a manual install requirement.txt file or something?
> 
> Edt: Should ask if VS 2022 is needed? I have 2019.

See here for manual installation:

https://github.com/anothermartz/Easy-Wav2Lip#for-other-configurations-untested-or-just-to-manually-install

I have only tested with the latest vs build tools.

**Comment by Echolink50** [comment]
Manual install confirmed working. Windows 10, Xeon 1240v5, 16GB Ram, RTX 2060 12GB.VRam. Installed VS 2022 and Cuda Toolkit 12.2. 
Used  "conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia"

Wow this is super fast and the quality is equal or better to the original Wav2lip. Now I have one minor issue. Every time you process a video it keeps using the same mouth/mask from the first video. It says "using previously detected face" or something like that. I didn't see a way to clear it on the config file or find the folder where the.masks are stored to delete them. Thanks for this implementation. It seems far superior.

Edit: Found a "last_detected_face.pkl" in the checkpoints folder. You can delete it and it will run face detection again. Adding an option in the config.ini to delete that file automatically before each run would be handy.

**Comment by anothermartz** [comment]
> Manual install confirmed working. Windows 10, Xeon 1240v5, 16GB Ram, RTX 2060 12GB.VRam. Installed VS 2022 and Cuda Toolkit 12.2. 
> Used  "conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia"
> 
> Wow this is super fast and the quality is equal or better to the original Wav2lip. Now I have one minor issue. Every time you process a video it keeps using the same mouth/mask from the first video. It says "using previously detected face" or something like that. I didn't see a way to clear it on the config file or find the folder where the.masks are stored to delete them. Thanks for this implementation. It seems far superior.
> 
> Edit: Found a "last_detected_face.pkl" in the checkpoints folder. You can delete it and it will run face detection again. Adding an option in the config.ini to delete that file automatically before each run would be handy. 

Thanks for the feedback. I'll definitely be adding  that :)

Edit: by the way it is supposed to delete the file if a new clip is added or if the padding has changed, but I think I messed something up with it. I'll still add the option to delete anyway as some people may use different clips with the same filename.

**Comment by anothermartz** [comment]
I believe I have fixed these issues in v8.1 and I have added use_previous_tracking_data which defaults to True.

If set to False it should delete the last tracking data regardless of whether or not the same file has been used.

If left at True it will only delete the last tracking data if the filename or padding has changed.
