### ISSUE TITLE
numpy ‘s question

### ISSUE THREAD

**Issue by argoo99** [anothermartz/Easy-Wav2Lip#11]
raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'complex_'?

how to use start wav2lip in local

**Comment by anothermartz** [comment]
I need to know more information, please tell me your:

OS
GPU
Python version 
VS BuildTools version

Also is that the entire error output? I don't see which lines of my code that it comes from.

**Comment by argoo99** [comment]
OS win 11 home
GPU 4080 12G
Python version 3.10.11
VS BuildTools version  2022

**Comment by anothermartz** [comment]
> OS win 11 home
> GPU 4080 12G
> Python version 3.10.11
> VS BuildTools version  2022

Perhaps the numpy version installed isn't the right one for this project, try this:

In the Easy-Wav2Lip folder, replace your requirements.txt with this version:

https://github.com/anothermartz/Easy-Wav2Lip/blob/v8.1/requirements.txt

Then delete installed.txt, run Easy-Wav2Lip.bat and let it reinstall Easy-Wav2Lip.

**Comment by argoo99** [comment]
this problem appear  again，The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'complex_'?
Processing failed! :( see line above 
Processing failed

**Comment by Echolink50** [comment]
> this problem appear again，The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'complex_'? Processing failed! :( see line above Processing failed

Try manual install. I used Windows 10 so 11 may be different. The .bat didn't work for me either. Install the prerequisites including FFMPEG, VS2022 and Cuda Toolkit 12.2, etc. Download Anaconda and run as Admin if you don't have it and follow the manual install instructions on the code page. After you create and activate the venv run this "conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia" then continue with the rest of the instructions.
