### ISSUE TITLE
Easy-Wav2lip apears to not be installed correctly, reinstall?

### ISSUE THREAD

**Issue by wesleyliwewa** [anothermartz/Easy-Wav2Lip#14]
Hello. 

When I try to install it by the Easy-Wav2Lip_v8.1.bat, I have some troubles.

It shows:

-----------------------------------------------

Welcome to Easy-Wav2Lip
Easy-Wav2lip apears to not be installed correctly, reinstall?
You will need around 2GB of free space.                                                                                 
Press any key to continue . . .
saving the large downloaded files
Easy-Wav2Lip\checkpoints\mobilenet.pth
Easy-Wav2Lip\checkpoints\README.md
2 File(s) copied
Cloning into 'Easy-Wav2Lip'...
remote: Enumerating objects: 1448, done.
remote: Counting objects: 100% (725/725), done.
remote: Compressing objects: 100% (366/366), done.
remote: Total 1448 (delta 465), reused 571 (delta 355), pack-reused 723
Receiving objects: 100% (1448/1448), 16.13 MiB | 12.20 MiB/s, done.
Resolving deltas: 100% (689/689), done.
temp\checkpoints\mobilenet.pth
temp\checkpoints\README.md
2 File(s) copied
'pip' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\AI\Easy-Wav2Lip\Easy-Wav2Lip\install.py", line 6, in <module>
    from IPython.display import clear_output
ModuleNotFoundError: No module named 'IPython'
Easy-Wav2lip apears to not be installed correctly, reinstall?
You will need around 2GB of free space.
Press any key to continue . . .
-----------------------------------------------

If I press any key, it keeps looping, and say:

Easy-Wav2lip apears to not be installed correctly, reinstall?
You will need around 2GB of free space.
Press any key to continue . . .

Is that the issue of "ModuleNotFoundError: No module named 'IPython'"?

If so, how to fix it?

Thank you!

**Comment by Echolink50** [comment]
The auto installer didn't work for me either. That was a while ago so maybe it's been updated since then. Try the manual install

https://github.com/anothermartz/Easy-Wav2Lip/issues/10

**Comment by wesleyliwewa** [comment]
Thank you, I could install it manually and running!
