### ISSUE TITLE
Unknown encoder 'h264_nvenc'

### ISSUE THREAD

**Issue by linhcentrio** [anothermartz/Easy-Wav2Lip#15]
converting to final video
[vost#0:0 @ 0x86c61c0] Unknown encoder 'h264_nvenc'
[vost#0:0 @ 0x86c61c0] Error selecting an encoder
Error opening output file /home/Easy-Wav2Lip/temp/output.mp4.
Error opening output files: Encoder not found
Traceback (most recent call last):
  File "/home/Easy-Wav2Lip/inference.py", line 694, in <module>
    main()
  File "/home/Easy-Wav2Lip/inference.py", line 662, in main
    subprocess.check_call([
  File "/home/Easy-Wav2Lip/venv/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-loglevel', 'error', '-i', 'temp/result.mp4', '-i', '/home/Easy-Wav2Lip/temp/huyen-anh_01.wav', '-c:v', 'h264_nvenc', '/home/Easy-Wav2Lip/temp/output.mp4']' returned non-zero exit status 8.
Processing failed! :( see line above 👆
Processing failed

**Comment by anothermartz** [comment]
Does result.mp4 in the temp folder work?

It's strange how it can use cuda to run everything but fail on nvenc encoding.

**Comment by pengfeiu** [comment]
I have the same problem, how do you solve it? result.mp4 is in the temp folder and can be opened, but there is no sound

**Comment by pengfeiu** [comment]
opening config.ini - customize accordingly then save and close it to continue!
config.ini closed - starting Easy-Wav2Lip...
Processing in.mp4 using in.wav for audio
imports loaded!
analysing audio...
182 frames to process
Using face detection data from last input
Starting...
Processing Wav2Lip: 100%|█████████████████████████████████████████| 415/415 [00:23<00:00, 17.46it/s]
converting to final video
Traceback (most recent call last):
  File "D:\aabbcc\Easy-Wav2Lip-8.1\inference.py", line 694, in <module>
    main()
  File "D:\aabbcc\Easy-Wav2Lip-8.1\inference.py", line 662, in main
    subprocess.check_call([
  File "C:\Users\wpf\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-loglevel', 'error', '-i', 'temp/result.mp4', '-i', 'D:\\aabbcc\\Easy-Wav2Lip-8.1\\temp\\in.wav', '-c:v', 'h264_nvenc', 'D:\\aabbcc\\Easy-Wav2Lip-8.1\\temp\\output.mp4']' returned non-zero exit status 3221225477.
in successfully lip synced! It will be found here:
D:\aabbcc\in\in_Easy-Wav2Lip.mp4
Execution time: 37s
opening config.ini - customize accordingly then save and close it to continue!

**Comment by netxor17** [comment]
Have you checked your CUDA version? As I've seen, the h264_nvenc encoder is available on CUDA 12.1 or above.
