### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by wesleyliwewa** [anothermartz/Easy-Wav2Lip#16]
Hi, I have another issue.

Some of the files I process, it will cause error. IndexError: list index out of range

Then it will stop.

May I know how to fix that?

Thank you.

Below is the detail.
-----------------------------------------------------------------

Processing slience-enhance.mp4 using news03-a.wav for audio
imports loaded!
analysing audio...
826 frames to process
Using face detection data from last input
mask size: 2.5, feathering: 3
Loading gfpgan
Starting...
Processing Wav2Lip:  56%|██████████████████████▉                  | 463/826 [08:50<06:55,  1.15s/it]
Traceback (most recent call last):
  File "C:\AI\Easy-Wav2Lip\inference.py", line 694, in <module>
    main()
  File "C:\AI\Easy-Wav2Lip\inference.py", line 593, in main
    for i, (img_batch, mel_batch, frames, coords) in enumerate(tqdm(
  File "C:\Users\wesley\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\AI\Easy-Wav2Lip\inference.py", line 469, in datagen
    face, coords = face_det_results[idx].copy()
IndexError: list index out of range
Processing failed! :( see line above 👆
Processing failed

**Comment by wesleyliwewa** [comment]
Hi, I think I found the issue, it was the source video. It was 25 frames/second, and I enhanced the video but save it in 30 frames/second accidentally, then it stopped at frame 463 every time. Once I change back to 25 frames/s, it works now. 
Thanks.

**Comment by wesleyliwewa** [comment]
Hi, I think I found the issue, it was the source video. It was 25 frames/second, and I enhanced the video but save it in 30 frames/second accidentally, then it stopped at frame 463 every time. Once I change back to 25 frames/s, it works now.
Thanks.

**Comment by qlixes** [comment]
> Hi, I think I found the issue, it was the source video. It was 25 frames/second, and I enhanced the video but save it in 30 frames/second accidentally, then it stopped at frame 463 every time. Once I change back to 25 frames/s, it works now. Thanks.

how to enchanced and save on different fps video source ? default Wav2Lip was 25 fps ? how to custom fps ? thank you a lot

**Comment by wesleyliwewa** [comment]
> how to enchanced and save on different fps video source ? default Wav2Lip was 25 fps ? how to custom fps ? thank you a lot

Hi, what I said about the default fps was the original video, it was 25fps. I edited and enhanced the video with another video editing program, and I did not notice that when I saved it, it was saved in 30fps in mp4 format.

And this new video causes error when using it with Wav2Lip. Once I found out and saved it again in 25fps, I got no issues.

However, on the other hand, it occasionally shows "IndexError: list index out of range" for any video, sometime I just restart Wav2Lip, using the same video, and it works later,

**Comment by qlixes** [comment]
> > how to enchanced and save on different fps video source ? default Wav2Lip was 25 fps ? how to custom fps ? thank you a lot
> 
> Hi, what I said about the default fps was the original video, it was 25fps. I edited and enhanced the video with another video editing program, and I did not notice that when I saved it, it was saved in 30fps in mp4 format.
> 
> And this new video causes error when using it with Wav2Lip. Once I found out and saved it again in 25fps, I got no issues.
> 
> However, on the other hand, it occasionally shows "IndexError: list index out of range" for any video, sometime I just restart Wav2Lip, using the same video, and it works later,

okay. thank you a lot.
