### ISSUE TITLE
any suggestions on Real Time or Pseudo Real Time? 

### ISSUE THREAD

**Issue by yslion** [anothermartz/Easy-Wav2Lip#22]
For example, a question-answering system with a virtual human, after being converted through WAv2lip, produces almost real-time output

**Comment by anothermartz** [comment]
Maybe it's possible with Wav2Lip in general at a low resolution with a really good GPU. but the method in which it operates would have to be heavily modified from this and any other project that I'm aware of.

The way this does it is it takes an existing complete audio file to analyse into something called mel chunks and then tracks a complete video of where the face is to crop it and then it applies wav2lip, then puts it back on the original video and compiles it. So for a real-time application it would have to analyse an ongoing stream to get a mel chunk, locate and crop the face and apply wav2lip then display it back onto the original frame. It'll be a lot of work and I'm not confident a lot of GPUs could do it in real time at a reasonable frame size and framerate.
