### ISSUE TITLE
how can I download the .pth and .pkl checkpoint files?

### ISSUE THREAD

**Issue by langkong** [anothermartz/Easy-Wav2Lip#24]
how can I download the .pth and .pkl checkpoint files?

Traceback (most recent call last):
  File "c:\maker\EasyWav2Lip\inference.py", line 117, in <module>
    with open(os.path.join('checkpoints','predictor.pkl'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints\\predictor.pkl'

**Comment by anothermartz** [comment]
The .pkl files are not downloaded, they are generated when Easy-Wav2Lip is installed.

See if there's a file called installed.txt in the Easy-Wav2Lip folder and delete it and try to run Easy-Wav2Lip.bat again then scroll up in the cmd window and look for 'initializing face detectors' and see if there's an error following it.

Which GPU do you have? If it isn't NVidia you will have to use the [Colab version](https://colab.research.google.com/github/anothermartz/Easy-Wav2Lip/blob/v8.1/Easy_Wav2Lip_v8.1.ipynb).
