### ISSUE TITLE
  File "D:\1\Easy-Wav2Lip\easy_functions.py", line 33, in get_video_details     length = float(info['format']['duration']) KeyError: 'duration'

### ISSUE THREAD

**Issue by cheng0009** [anothermartz/Easy-Wav2Lip#25]
Traceback (most recent call last):
  File "D:\1\Easy-Wav2Lip\run.py", line 81, in <module>
    in_width, in_height, in_fps, in_length = get_video_details(video_file)
  File "D:\1\Easy-Wav2Lip\easy_functions.py", line 33, in get_video_details
    length = float(info['format']['duration'])
KeyError: 'duration'

**Comment by anothermartz** [comment]
It was unable to find the length of the video file, can you specify the details of the file, is it a video or an image?
