### ISSUE TITLE
Not working after click 2 step

### ISSUE THREAD

**Issue by dominkomi** [anothermartz/Easy-Wav2Lip#28]
Hello, today Wav2Lip has bug.
After 1 step is done, 2 step inform about not finished 1 step (red button) when is already done...
Last months everything was works so well :) So i decided to put this information there to help resolve this problem.
Thanks!
![Screenshot 2024-03-13 21-28-32](https://github.com/anothermartz/Easy-Wav2Lip/assets/163350329/8b102744-d5b9-4b79-b8db-094232128307)

**Comment by Akibajack** [comment]
yes mee too

**Comment by Novis4** [comment]
me too

**Comment by anothermartz** [comment]
Thanks for letting me know! I'll have a look at this tonight, I guess something updated somewhere and I need to update my code to work with the new format.

**Comment by anothermartz** [comment]
Thanks for letting me know! I'll have a look at this tonight, I guess something updated somewhere and I need to update my code to work with the new format.

**Comment by jaybatsby1** [comment]
Me too

**Comment by anothermartz** [comment]
Apologies, I didn't manage to get to my PC yesterday but I did this evening and have found a hacky solution for the mean time until I properly get to the bottom of it!

https://github.com/anothermartz/Easy-Wav2Lip/releases/tag/v8_1_quickfix

**Comment by anothermartz** [comment]
Can someone please try this colab to see if it works?

https://colab.research.google.com/github/anothermartz/Easy-Wav2Lip/blob/v8.1/Easy_Wav2Lip_v8.1_fixed.ipynb

I think it should. but I'm unable to test it right now as google kicked me off using a GPU for a while unless I pay but as it's just to test this one thing I hope you understand I'm not quite willing to!

**Comment by Novis4** [comment]
> Can someone please try this colab to see if it works?
> 
> https://colab.research.google.com/github/anothermartz/Easy-Wav2Lip/blob/v8.1/Easy_Wav2Lip_v8.1_fixed.ipynb
> 
> I think it should. but I'm unable to test it right now as google kicked me off using a GPU for a while unless I pay but as it's just to test this one thing I hope you understand I'm not quite willing to!

If he writes that the GPU has run out, then it is enough to change the Google account and it will continue to work. I'll try it now and write the result

**Comment by Novis4** [comment]
![Screenshot_1](https://github.com/anothermartz/Easy-Wav2Lip/assets/53331492/90ccc43f-1261-432f-b8d9-46585c93caba)

**Comment by dominkomi** [comment]
Still not working :(
![Screenshot 2024-03-16 22-27-15](https://github.com/anothermartz/Easy-Wav2Lip/assets/163350329/ce50e18e-9938-4e30-8241-ae1ad523432c)

**Comment by anothermartz** [comment]
ok thank you, I'll bite the bullet and get colab pro for a month as I just found out they've added some AI coding stuff which would help me too!

Edit: argh, AI stuff is for US only ☹️

**Comment by Novis4** [comment]
> ok thank you, I'll bite the bullet and get colab pro for a month as I just found out they've added some AI coding stuff whihch would help me too!

Do you know how to solve the problem with the square under the chin? I was able to partially solve this, but it doesn't help everywhere.

**Comment by Novis4** [comment]
I also tried to add a model for recognizing body parts to make a clear lip area, but they were fighting among themselves

**Comment by anothermartz** [comment]
Ok it should work now!

https://colab.research.google.com/github/anothermartz/Easy-Wav2Lip/blob/v8.1/Easy_Wav2Lip_v8.1_fixed.ipynb

I think I'll make an 8.2 to signify it working, alongside the local version which has been fixed too.

> Do you know how to solve the problem with the square under the chin? I was able to partially solve this, but it doesn't help everywhere.

Please open as a new issue to discuss this :)

**Comment by dominkomi** [comment]
Thanks, finally works :)

**Comment by dominkomi** [comment]
Is there any way to improve quality - bitrate? :( Unfortunatelly 2mbs is so low, and sometimes is big difference beetween oryginal video.

**Comment by anothermartz** [comment]
> Is there any way to improve quality - bitrate? :( Unfortunatelly 2mbs is so low, and sometimes is big difference beetween oryginal video.

This is an interesting topic, can you please make it as a new issue for us to discuss?
