### ISSUE TITLE
Can this  repo be deployed on our computer?

### ISSUE THREAD

**Issue by Pythonpa** [anothermartz/Easy-Wav2Lip#3]
Can this repo be deployed on our PC?

**Comment by anothermartz** [comment]
I've made this specifically for colab so there's a good chance things won't work locally but I haven't tried.

Edit:
I know for a fact that this code won't work if ran locally as it relies far too much on the specific colab input I'm giving.

I am however interested in making it work locally, but that will be difficult for me and so it'll probably take a while!

**Comment by Pythonpa** [comment]
> 

ok,thanks ,I will have a try.

**Comment by anothermartz** [comment]
I've been told by someone that they got this to work locally, I'm not sure what their method is and they did need a bit of assistance, but they managed it!

Once I'm happy with the functionality of the colab, I will endevour to make a local branch to make it as easy as possible.

My GPU is actually better than the colab T4 so it'd benetfit myself greatly! I just worry about the interface, I feel like I'd have to use webui which will be a whole new learning experience.

**Comment by anothermartz** [comment]
v8 now supports running on local hardware:

https://github.com/anothermartz/Easy-Wav2Lip/releases/tag/v8_release

I even make an auto-installer for Windows machines!
