### ISSUE TITLE
Step 2 still doesn't work.

### ISSUE THREAD

**Issue by Mishmallow11** [anothermartz/Easy-Wav2Lip#30]
Sorry for the persistence, I’ve been waiting for the second day for the problem to be corrected. I saw your previous messages, you promised to fix it as soon as you get to the computer. I hope everything is okay with you. Looking forward to the update!

Thank you very much!

**Comment by arthurcaio92** [comment]
Please wait patiently! It is a FREE tool that he is providing to us, and he needs time to fix the issue.

**Comment by anothermartz** [comment]
Duplicate of issue #28 I will update that thread about this issue.
