### ISSUE TITLE
Easy-Wav2Lip for Mac OS (test version available!)

### ISSUE THREAD

**Issue by Anastasianewbie** [anothermartz/Easy-Wav2Lip#35]
Hello, please tell me, I’m new to the topic of deepfakes, I’ve been figuring it out for a week now, I’ve made some progress, I found out that a new Easy-Wav2Lip has been released and I want to ask, is it possible to use this program on a MacBook? If not, what software do I need to use Easy-Wav2Lip, please give a more detailed answer

**Comment by anothermartz** [comment]
It doesn't work with MacOS because cuda isn't available on macos, but I am interested in giving this pull request for the original Wav2Lip a try:

https://github.com/Rudrabha/Wav2Lip/pull/630

I don't have a mac to test with though so It'll be untested. I'll update this thread when I add in the code :)

**Comment by anothermartz** [comment]
I've incorporated the tweaks that should enable cpu and mps support, theoretically allowing for MacOS support, can you give it a try?

1. Make sure the following are installed and can be accessed via your terminal:
      * Python 3.10 (I have only tested [3.10.11](https://www.python.org/ftp/python/3.10.11/python-3.10.11-macos11.pkg) - other versions may not work!)
      * [Git](https://git-scm.com/download/mac)

2. Open Terminal and cd to the folder you want to install Easy-Wav2Lip, then:

Install and first run (makes a venv and installs ffmpeg too):
```
python3.10 -m venv Easy-Wav2Lip-venv
source Easy-Wav2Lip-venv/bin/activate
python -m pip install --upgrade pip
python -m pip install requests
for file in ffmpeg ffprobe ffplay; do
    curl -O "https://evermeet.cx/ffmpeg/${file}-6.1.1.zip"
    unzip "${file}-6.1.1.zip"
done
mv -f ffmpeg ffprobe ffplay /Easy-Wav2Lip-venv/bin/
git clone -b macOSTest https://github.com/anothermartz/Easy-Wav2Lip.git
cd Easy-Wav2Lip
pip install -r requirements.txt
python install.py
./run_loop.sh

```

Then to run for future sessions (cd to the same place you did to before):
```
source Easy-Wav2Lip-venv/bin/activate
cd Easy-Wav2Lip
./run_loop.sh
```

Please let me know if this works as I have no Mac to test with.

**Comment by anothermartz** [comment]
MacOS should now be supported in v8.3, ARM processors will benefit from the mps support.
