### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'degradations.py'

### ISSUE THREAD

**Issue by gavid0124** [anothermartz/Easy-Wav2Lip#38]
when ssh excute command: python install.py 
display these errors,but '/home/ps/miniconda3/envs/wav2lip/lib/python3.11/site-packages/degradations.py'
has this file'degradations.py' :
Traceback (most recent call last):
  File "/home/ps/miniconda3/envs/wav2lip/lib/python3.11/shutil.py", line 853, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'degradations.py' -> '/home/ps/miniconda3/envs/wav2lip/lib/python3.11/site-packages/degradations.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Easy-Wav2Lip/install.py", line 38, in <module>
    move_and_replace_file_to_basicsr(file_to_replace)
  File "/Easy-Wav2Lip/install.py", line 31, in move_and_replace_file_to_basicsr
    shutil.move(file_name, destination)
  File "/home/ps/miniconda3/envs/wav2lip/lib/python3.11/shutil.py", line 873, in move
    copy_function(src, real_dst)
  File "/home/ps/miniconda3/envs/wav2lip/lib/python3.11/shutil.py", line 448, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ps/miniconda3/envs/wav2lip/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'degradations.py'

**Comment by anothermartz** [comment]
I think it's complaining about the degradations.py file in the Easy-Wav2Lip folder, is that there?

It also looks like you're using python 3.11 and in my experience that causes version incompatibility with some modules so if you still have issues try installing and using python 3.10.

**Comment by qp910** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PycharmProjects\Easy-Wav2Lip\install.py", line 38, in <module>
    move_and_replace_file_to_basicsr(file_to_replace)
  File "D:\PycharmProjects\Easy-Wav2Lip\install.py", line 31, in move_and_replace_file_to_basicsr
    shutil.move(file_name, destination)
  File "D:\Program Files\anaconda3\envs\ewl\lib\shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "D:\Program Files\anaconda3\envs\ewl\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "D:\Program Files\anaconda3\envs\ewl\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'degradations.py'

(ewl) D:\PycharmProjects\Easy-Wav2Lip>python -V
Python 3.10.11

**Comment by gavid0124** [comment]
> I think it's complaining about the degradations.py file in the Easy-Wav2Lip folder, is that there?
> 
> It also looks like you're using python 3.11 and in my experience that causes version incompatibility with some modules so if you still have issues try installing and using python 3.10.

Thanks, I find the reason,  loss the file 'degradations.py' when clone the code.

**Comment by gavid0124** [comment]
I have found another problem, the generated videos are not very clear, especially around the mouth area. Here are screenshots of the original video and the new video:
![20240328175946(original)](https://github.com/anothermartz/Easy-Wav2Lip/assets/8635721/11531427-b58b-47ef-a9b1-a5cca0eaac87)
![20240328180228(new)](https://github.com/anothermartz/Easy-Wav2Lip/assets/8635721/6a82ab75-b847-4947-9ac4-c6f1d163688f)

**Comment by anothermartz** [comment]
> I have found another problem, the generated videos are not very clear, especially around the mouth area.

Wav2Lip is pretty inherently a low resolution tool, I have implemented gfpgan upscaling to combat this, but it isn't flawless.

If you're using the "Fast" or "Improved" quality options, this is just Wav2Lip in its default low resolution and you would need to use "Enhanced" quality option to enable gfpgan upscaling.

If you have that enabled and it still looks like this, it's perhaps that the input is just too high resolution for how large the face is in the frame and you may have to utelise the "output_height" option to "half resolution" or the number of vertical pixels.

Also consider using wav2lip_gan as the [wav2lip_verion option](https://github.com/anothermartz/Easy-Wav2Lip/tree/v8.2?tab=readme-ov-file#wav2lip_version) as the output resolution will be higher at the cost of accuracy.

If you want to discuss this further, please make it a new issue as it is unrelated to the degradations.py issue that this thread is really about.

**Comment by anothermartz** [comment]
> File "/home/ps/miniconda3/envs/wav2lip/lib/python3.11/shutil.py", line 853, in move
> os.rename(src, real_dst)
> FileNotFoundError: [Errno 2] No such file or directory: 'degradations.py' ->

I think the issue was that the degradations.py file was moved instead of copied so once it has been done, it can't be done again unless you redownload it.


I've updated the code so that it copies now so download [install.py](https://raw.githubusercontent.com/anothermartz/Easy-Wav2Lip/v8.2/install.py) and [degradations.py](https://raw.githubusercontent.com/anothermartz/Easy-Wav2Lip/v8.2/degradations.py) and put them into your Easy-Wav2Lip folder and try again.

I think that change should fix this issue, feel free to comment if you still experience this and I may open it again.

**Comment by gavid0124** [comment]
> Wav2Lip is pretty inherently a low resolution tool, I have implemented gfpgan upscaling to combat this, but it isn't flawless.
> 
> If you're using the "Fast" or "Improved" quality options, this is just Wav2Lip in its default low resolution and you would need to use "Enhanced" quality option to enable gfpgan upscaling.
> 
> If you have that enabled and it still looks like this, it's perhaps that the input is just too high resolution for how large the face is in the frame and you may have to utelise the "output_height" option to "half resolution" or the number of vertical pixels.
> 
> Also consider using wav2lip_gan as the [wav2lip_verion option](https://github.com/anothermartz/Easy-Wav2Lip/tree/v8.2?tab=readme-ov-file#wav2lip_version) as the output resolution will be higher at the cost of accuracy.
> 
> If you want to discuss this further, please make it a new issue as it is unrelated to the degradations.py issue that this thread is really about.



> > File "/home/ps/miniconda3/envs/wav2lip/lib/python3.11/shutil.py", line 853, in move
> > os.rename(src, real_dst)
> > FileNotFoundError: [Errno 2] No such file or directory: 'degradations.py' ->
> 
> I think the issue was that the degradations.py file was moved instead of copied so once it has been done, it can't be done again unless you redownload it.
> 
> I've updated the code so that it copies now so download [install.py](https://raw.githubusercontent.com/anothermartz/Easy-Wav2Lip/v8.2/install.py) and [degradations.py](https://raw.githubusercontent.com/anothermartz/Easy-Wav2Lip/v8.2/degradations.py) and put them into your Easy-Wav2Lip folder and try again.
> 
> I think that change should fix this issue, feel free to comment if you still experience this and I may open it again.

Thank you, I will open a new issue.
