### ISSUE TITLE
"Processing failed" immediately after "imports loaded".

### ISSUE THREAD

**Issue by anothermartz** [anothermartz/Easy-Wav2Lip#39]
<img width="416" alt="image" src="https://github.com/anothermartz/Easy-Wav2Lip/assets/124433894/77d4ba47-0d4d-4a89-9473-802e2515b74e">

_Originally posted by @KeraiSensei in https://github.com/anothermartz/Easy-Wav2Lip/issues/37#issuecomment-2023326510_

**Comment by anothermartz** [comment]
Please give more details about this, do any other files work?

**Comment by KeraiSensei** [comment]
Nah, nothing works, using 8.2, any video crashing like this

**Comment by anothermartz** [comment]
> Nah, nothing works, using 8.2, any video crashing like this

Did you use the Easy-Wav2Lip.bat or did you install manually?

I think this is an issue with the imports loading which can result from them not being installed properly and that can be from the wrong python version or another requirement not being met.

**Comment by KeraiSensei** [comment]
Using collab

**Comment by anothermartz** [comment]
> Using collab 
> 

I can't replicate the issue, can you make sure you're using the unmodified v8.2 colab found on the main project page?

-I'm closing this issue for now, feel free to comment if you're still experiencing it.
