### ISSUE TITLE
Easy_Wav2Lip_v8.1.ipynb 

### ISSUE THREAD

**Issue by Zbhatti2** [anothermartz/Easy-Wav2Lip#46]
Step 1 Cell ran successfully. But in step 2, the following error occurs; 

An exception has occurred, use %tb to see the full traceback.

SystemExit: Step 1 has not been run in this instance! Please run step 1 each time you disconnect from a runtime.
/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

installed.txt file ???

**Comment by anothermartz** [comment]
v8.2 fixes this issue:

### Google Colab:
[https://colab.research.google.com/github/anothermartz/Easy-Wav2Lip/blob/v8.2/Easy_Wav2Lip_v8.2.ipynb](https://colab.research.google.com/github/anothermartz/Easy-Wav2Lip/blob/v8.2/Easy_Wav2Lip_v8.2.ipynb)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/anothermartz/Easy-Wav2Lip/blob/v8.2/Easy_Wav2Lip_v8.2.ipynb)
