### ISSUE TITLE
Bro I have no ill intentions. Your profile picture looks a little bit scary

### ISSUE THREAD

**Issue by SakuraMaiii** [anothermartz/Easy-Wav2Lip#48]
Thanks for your great contribution

**Comment by anothermartz** [comment]
It's from my first test video of trying to drive a face in a video with another face from a video:

https://www.youtube.com/watch?v=bbyTYMWamoA

It's something I tried a while back and couldn't get very good results (as seen in that video), but I've been looking into it again recently.

I see projects where you can face swap an image of a face onto a video of a face, but not being able to drive the facial expressions of a face in a video, with another video of a face. I think it could be quite a fun tool for video creators.
