### ISSUE TITLE
Easy Wav2Lip colab -json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by xzants** [anothermartz/Easy-Wav2Lip#50]
I run v8.2 with Colab to appear the following error.I use the video format is MP4, AVI, WMV, MPG. Video resolution is 480p, frame rate 24fps. Size 9:16
----
Traceback (most recent call last):
  File "/content/Easy-Wav2Lip/run.py", line 98, in <module>
    in_width, in_height, in_fps, in_length = get_video_details(video_file)
  File "/content/Easy-Wav2Lip/easy_functions.py", line 19, in get_video_details
    info = json.loads(result.stdout)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
<img width="1308" alt="iShot_2024-04-06_14 01 12" src="https://github.com/anothermartz/Easy-Wav2Lip/assets/28720306/7e0d504f-3c6a-4022-86bb-2cc737849ab0">

**Comment by anothermartz** [comment]
Sorry for the late reply.

You aren't actually selecting the files, just the folders!

I'll add a check for this in the next version.

video_file should be: 
`/content/input/I1vp6-Ingu5.wmv`

**Comment by xzants** [comment]
Sorry for the late reply.
oh! thanks... let me see see

**Comment by xzants** [comment]
Thank you very much. The problem has been resolved and can be used normally.

**Comment by anothermartz** [comment]
I've added a directory check in v8.3 that should handle this issue:

https://github.com/anothermartz/Easy-Wav2Lip/commit/ad637888d8c26d1133e0703b4291a6bdcd171a1f
