### ISSUE TITLE
Kaggle problem

### ISSUE THREAD

**Issue by testujemai** [anothermartz/Easy-Wav2Lip#73]
I have problem with running it on Kaggle. I thought if we can run it on Colab there is possible way to run it on Kaggle. Ofc I changed folders and tryed a lot of solutions with installing libxcb - did not work.

Processing 35685012a_15-54-52.mp4 using 4.wav for audio
imports loaded!     
analysing audio...
500 frames to process
Using face detection data from last input                                                           
mask size: 1.5, feathering: 1
Loading gfpgan
Starting...
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/opt/conda/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Processing failed! :( see line above 👆
Consider searching the issues tab on the github:
https://github.com/anothermartz/Easy-Wav2Lip/issues

**Comment by gaoleihero** [comment]
I have encountered the same problem, what should I do
